global:
  resolve_timeout: 5m
  smtp_smarthost: smtp.gmail.com:587
  smtp_from: nevint3195@gmail.com
  smtp_auth_username: nevint3195@gmail.com
  smtp_auth_password: ""
  smtp_require_tls: true

route:
  receiver: email-alerts
  group_by: ['alertname', 'namespace']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

  routes:
  - matchers:
    - severity="critical"
    receiver: email-alerts
    repeat_interval: 1h

receivers:
- name: email-alerts
  email_configs:
  - to: nevint3195@gmail.com
    send_resolved: true

