apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-canary
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
      version: canary
  template:
    metadata:
      labels:
        app: product
        version: canary
    spec:
      containers:
      - name: product
        image: 743296984102.dkr.ecr.ap-south-1.amazonaws.com/myproject-app:v2
        env:
        - name: APP_VERSION
          value: "v2-canary"
        ports:
        - containerPort: 3000  
