apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-stable
  labels:
    app: product
    track: stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
      track: stable
  template:
    metadata:
      labels:
        app: product
        track: stable
    spec:
      containers:
      - name: product-service
        image: 743296984102.dkr.ecr.ap-south-1.amazonaws.com/myproject-app:IMAGE_TAG
        ports:
        - containerPort: 8080
