apiVersion: v1
kind: Service
metadata:
  name: product-blue
  namespace: ecommerce
spec:
  selector:
    app: product
    version: blue
  ports:
    - port: 80
      targetPort: 5678
  type: ClusterIP

